#ifndef __DIANRU_OBCODE_H__
#define __DIANRU_OBCODE_H__
#define getDianruDeviceOrientation getCompareOnion
#define setDianruRequestLaseTimeWithUrl setShowCake
#define dianruViewload ReadWebView
#define dianruStartEGOUpdate CompileBread
#define dianruSpendScoreResultCallback RunNoodles
#define getDianruMainBounds getDecorateTable
#define dianruObjectForKey CompileSegment
#define dianruDidJumpedView FallLabel
#define YQL_V HoldBear
#define getDianruAppId getDanceTableCell
#define dianruFindview RunEgg
#define YQLHttpActionExecer CollectSubject
#define dianruWithMySelf DeleteTableCell
#define YQLAlignCenter BorrowProgress
#define YQLANIMATION_TYPE ApendPotato
#define dianruQueryString IndexKilometer
#define dianruResizeToFit ProductSwitch
#define dianruAddRefreshView FindFeature
#define YQLMacros CreateLiberty
#define dianruEnable GetDessert
#define dianruRequestBlock EndWithNavigationBar
#define dianruImageFor NeedSnake
#define dianruTimeout DoDessert
#define YQLTextureInfo ApendTableCell
#define dianruExpire MaintainWhale
#define YQLViewUnknow NextRice
#define dianruParseEvent MakeWindow
#define dianruParseFloat SetExperience
#define dianruDidReportedView GetSnake
#define YQLTextureVertical ReplaceOnion
#define YQLReqestResultType IteratorView
#define YQLViewCell KillBear
#define getDianruSpendScore getNextCarrot
#define YQLTextureHorizontal DoBroccoli
#define dianruShareIstance SleepPotato
#define dianruActions SleepTree
#define dianruBuildWithName FowardDessert
#define setDianruNode setCostTableViewCell
#define dianruDuration FindTableViewCell
#define YQLNotificationAction FunctionTrumpet
#define dianruExec SleepAlertView
#define dianruLoadView CostLiberty
#define dianruApplicationKey DecorateAchieve
#define addDianruStyle StartWithFlower
#define dianruRequestSpace StudyNavigationBar
#define dianruCreate InviteActivityView
#define dianruContext PrintWeed
#define dianruCancel LockFeature
#define YQLAlignLeft CreateView
#define YQLViewText BorrowExperience
#define initWithDianruContext initBuildKilometer
#define dianruName DeleteVoice
#define dianruParseTextAttr CatchCake
#define getDianruMacAddress getHashWindow
#define setDianruArrowData setCrashBear
#define YQLHttpRequest CatchAlertView
#define dianruSubview FunctionPotato
#define setDianruDelegateNull setQuerySpider
#define dianruReadNetDataTaskFor InviteRadish
#define dianruStopLoadAnimation StartWithParrot
#define dianruFsPath BlowSubject
#define dianruEnableUseRadius AddCake
#define dianruDidDataReceivedView BiteAlertView
#define YQLActionNode LockLaugh
#define dianruWakeup LookBread
#define YQLFontBold GetMemory
#define YQLViewSection CompileImage
#define YQLUrlCache GetPotato
#define dianruMovieFinishedCallback CloneCell
#define YQLViewSimple MakeTableCell
#define dianruLoadData SetToolBar
#define dianruHide BuildVoice
#define dianruResult startWithSlider
#define dianruRemove MakeDessert
#define YQLFontStyle_ALL DevelopLiberty
#define YQLViewDelegate CostMemory
#define refreshDianruTableHeaderDidTriggerRefresh DanceSpider
#define dianruRect CloneBroccoli
#define dianruStartRotation ParseFlower
#define YQLViewTable LookProgress
#define addDianruChild ShowPlant
#define dianruPurge DeleteWhale
#define YQLHttpAction FowardImage
#define YQLOPullRefreshLoading StudyVoice
#define dianruText LookSubject
#define dianruImage EndWithAdvice
#define _dianruBuild CloneSegment
#define setDianruImageWithContent setParseProgress
#define dianruExecuteAnimation CoverPlant
#define getDianruLocation getCostAlertView
#define YQLRefreshTableHeaderDelegate BrushWebView
#define dianruInitialize NextWindow
#define setDianruResult setStartWithSlider
#define YQLSectionView AnswerPumpkin
#define dianruStopEGOUpdate SleepLaugh
#define YQLFontDELETE BrushButton
#define refreshDianruScrollViewDidEndDragging NeedCell
#define dianruTimes BorrowRice
#define dianruParent SleepImage
#define dianruHandleSingleFingerEvent DecorateInterest
#define YQLNode DecorateCarrot
#define YQLScriptRunner AddPlant
#define YQLAnimationView FunctionWeed
#define YQLViewAnimation GeneralCell
#define dianruTarget MatchBroccoli
#define getDianruQueryString getCloneRadish
#define getDianruReportUrl getDevelopWebView
#define dianruParseActionNode CompareBear
#define dianruUpdateContent CreateSegment
#define dianruCutStr HoldInterest
#define setDianruRefreshArrowImage setStartWithCountry
#define getDianruScore getStudyInterest
#define YQLMediaView MakeSlider
#define refreshDianruTableHeaderDataSourceIsLoading MaintainButton
#define YQLTexture NeedTree
#define YQLViewInterstitial CutInterest
#define dianruUrl CrashSegment
#define dianruLocalIPAddress IteratorWebView
#define refreshDianruScrollViewDataSourceDidFinishedLoading DoWhale
#define dianruWebViewCallBack StartWithCache
#define dianruDataFor IteratorTable
#define YQLDelegate ReplaceSegment
#define dianruFsDirectory BrushTrumpet
#define dianruEncryptWithText PutSubject
#define YQLTableSectionView IndexTrumpet
#define setDianruState setPrintBread
#define dianruDecodeToUrl InviteCountry
#define dianruLocation replaceNoise
#define YQLTextureType MakePicker
#define dianruDidMainCloseView PermitChicken
#define dianruEvent SetAlertView
#define YQLViewHtml WaitTomato
#define YQLOPullRefreshPulling MatchExperience
#define dianruExit ReplaceSnake
#define dianruParseBackground ParseNavigationBar
#define YQLViewRoot AddRice
#define YQLAction AddSpider
#define YQLFactory BuildProgress
#define YQLOrientation CoverLiberty
#define dianruDidViewCloseView PutForest
#define dianruDeviceOrientationDidChange DecorateWindow
#define YQLTextureSimple LookInterest
#define getDianruImage getIteratorChicken
#define dianruRun LoadInterest
#define dianruWrite CollectBelieve
#define YQLInterstitialView CollectRadish
#define dianruURLEncodedString BeatActivityView
#define dianruAppuserid CoverBread
#define dianruExecOne LoadFlower
#define YQLViewAction GeneralSpider
#define getDianruMachineName getParseSpider
#define dianruShowLoadAnimation BuildOnion
#define dianruKeyForString PermitWindow
#define dianruWithData BiteFeature
#define dianruMoviePlayerLoadStateChanged CatchTableCell
#define dianruFrame replaceNavigationBar
#define YQLSimpleView KillTabBar
#define YQLUIModel CreateLaugh
#define dianruDeviceString GetFeature
#define dianruCreateWithView IndexWhale
#define dianruShow CatchInterest
#define dianruOn SleepPiano
#define dianruReportData DevelopSubject
#define dianruParseHex DanceActivityView
#define dianruCacheTimeList EndWithKilometer
#define YQLScript MatchPotato
#define dianruHTTPResultCallback DevelopExperience
#define dianruScoreResultCallback AddBroccoli
#define dianruSuspend CreateCache
#define getDianruTimestamp getDoCake
#define dianruDelegate FowardSpider
#define dianruWithUrl SetButton
#define dianruWithRequst BrushLaugh
#define getDianruOSVersion getIteratorNavigationBar
#define dianruStartAni FunctionAlertView
#define YQLView CallSpider
#define YQLFontStyleNode ChangeKilometer
#define dianruStopRotation DecorateButton
#define dianruDisposeContent NextSegment
#define dianruFindView DeleteSwitch
#define dianruWithCallback HoldOnion
#define dianruURLDecodedString CutRadish
#define getDianruUserId getChangeBelieve
#define YQLTextureLoop CostWindow
#define YQLViewNode HashSnake
#define dianruNode costTableViewCell
#define dianruStopAnimation ReplaceActivityView
#define dianruUrlToDecode HoldLaugh
#define dianruParseInsets DoLabel
#define YQLAlign HashTree
#define dianruRegistClickEvent WaitButton
#define YQLViewLoader CollectWindow
#define refreshDianruScrollViewDidScroll PutInterest
#define YQLTextView CollectLiberty
#define YQLEncryptUtil CrashPicker
#define YQLViewUtil CollectBroccoli
#define YQLRefreshTableView_LastRefresh IndexProgress
#define YQLLabelUpdate CompareView
#define dianruView DevelopDessert
#define YQLFontNormal HoldCache
#define dianruDecryptWithText DanceBear
#define dianruDidViewOpenView HashTableCell
#define YQLContext RunKilometer
#define YQLGTMBase64 ParseTableViewCell
#define dianruParseStyleAttr NeedCarrot
#define YQLOPullRefreshNormal NextDolphin
#define YQLTALKINGTYPE SleepSubject
#define YQLFontUnderLine NeedButton
#define YQLSdkInfo ServeParrot
#define dianruContent killSlider
#define setDianruContent setKillSlider
#define dianruData CollectDessert
#define dianruForKey CallFeature
#define onDianruAdClickADID CutWebView
#define getDianruScreenFrame getIndexPotato
#define dianruDoneLoadingTableViewData AnswerVoice
#define dianruLayer SetWeed
#define dianruClose ReadAchieve
#define YQLTalkingDataAction PrintDessert
#define dianruCode QueryLaugh
#define refreshDianruLastUpdatedDate GetImage
#define getDianruHttpFail getLookCountry
#define YQL_TK_CLICK QueryCake
#define dianruImageResultCallback ReplaceButton
#define YQLViewType DanceCake
#define dianruDecode FindProgress
#define YQLTableCell DeleteLiberty
#define YQLCacheRequest CoverView
#define YQL_TK_DISPLAY DanceSlider
#define YQLStyleNode StudyFeature
#define YQLEngine CostSnake
#define dianruReadLocationDataTaskFor WaitCell
#define dianruScreenRotation SleepAchieve
#define dianruEnableRequestWithUrl DeleteProgress
#define YQLTextureFull HashPumpkin
#define YQLOpenAction CrashTree
#define YQLViewFactory IteratorLabel
#define YQLBorder LoadForest
#define YQLFileSystem PutDessert
#define dianruIsModify ProductCache
#define dianruCenter ReplaceBear
#define YQLViewImage StartWithChicken
#define dianruReloadTableViewDataSource FallNoise
#define YQLDeviceInfo ParseWindow
#define dianruParseStyle HashPlant
#define YQLFontStyle PutBroccoli
#define setDianruLocation getReplaceNoise
#define dianruParseBorder PrintTableViewCell
#define dianruParseView SetCountry
#define dianruFormat ShowOnion
#define dianruObject DanceSubject
#define dianruDidClickedView AddAlertView
#define YQLAlignRight MatchDessert
#define dianruKey WaitForest
#define dianruMasks SleepMemory
#define YQLRefreshTableHeaderView MaintainProgress
#define dianruPadding PutBear
#define dianruMethod LockWindow
#define refreshDianruTableHeaderDataSourceLastUpdated HashNoise
#define dianruSpaceUrl BlowButton
#define dianruWith GetBear
#define dianruDrawType SetSlider
#define dianruLocalWiFiAvailable PutButton
#define dianruSubviews SetCake
#define YQLPullRefreshState DoSpider
#define dianruLoadani CostActivityView
#define getDianruWithIDFA getShowSpider
#define dianruParseRect RunTabBar
#define dianruParseColor PutBelieve
#define dianruTimerAction ReadCarrot
#define onDianruAdDisplayADID MaintainTree
#define dianruTo AnswerSpider
#define dianruLoad QuerySnake
#define YQLTalkingData GeneralNoise
#define dianruParseAlign ProductSnake
#define YQLHtmlView FowardPlant
#define dianruDecodeOne PermitTomato
#define dianruBuild BiteWhale
#define addDianruEvent ParseBread
#define dianruChecksum2 ParseWhale
#define dianruAddCallback SleepBear
#define dianruChecksum1 CoverEgg
#define dianruBind BrushTableCell
#define dianruDrawTexture LoadWhale
#define setDianruImageWithUrl setWaitPlant
#define isDianruJailbroken BlowTrumpet
#define dianruValue CutSubject
#define getDianruBaseUrl getDancePicker
#define dianruCarrierName CompareTableViewCell
#define dianruSubType FindWindow
#define YQLTableView DanceAdvice
#define dianruParseFontStyle CatchView
#define YQLViewMedia NextMemory
#define dianruClearup BorrowMemory
#define dianruAddCell GeneralPlant
#define dianruState printBread
#define YQLAlertAction PermitWeed
#define dianruCloseMain CallExperience
#define dianruType LoadDessert
#define YQLUtil BlowVoice
#define YQLEventManager BlowAlertView
#define setDianruViewNode setReplaceWeed
#define setDianruFrame setReplaceNavigationBar
#define YQLAnimationAction IndexSubject
#define YQL_TK_UNKNOW PrintWindow
#define dianruCallback CompileDamage
#define YQLDataCache LookTableViewCell
#define YQLLoader MakeRadish
#define dianruStartAniType BlowAchieve
#define YQLOpenUDID MatchPiano
#define YQLLocation NextKilometer
#define YQL_H MakeCache
#define dianruUpdate StudyDamage
#define dianruParseViewType BiteActivityView
#define dianruStartAnimation RunView
#define YQLImageView BorrowTableCell
#define YQLSDK CreateCarrot
#define YQLWebView EndWithBroccoli
#define dianruParseTextureType KillWebView
#define dianruRequest ProductForest
#define dianruCheckIsNeedModify DeleteTree
#define dianruFileIsExists CoverSubject
#endif /*__DIANRU_OBCODE_H__*/
